CREATE TABLE moderation_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    target_id VARCHAR(32) NOT NULL,
    target_tag VARCHAR(37) NOT NULL,
    moderator_id VARCHAR(32) NOT NULL,
    moderator_tag VARCHAR(37) NOT NULL,
    action VARCHAR(16) NOT NULL,
    reason TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;